<?php

/**
 * @file
 * General hook implementations.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_spreadsheet_ingest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'islandora_spreadsheet_ingest.templates':

      return <<<EOHELP
<p>Here you can add or remove spreadsheet ingest templates.</p>
EOHELP;

    case 'islandora_spreadsheet_ingest.ingest':

      return <<<EOHELP
<p>Here you can add or remove spreadsheet ingests.</p>
EOHELP;

  }
}
