<?php

/**
 * @file
 * Main module entry points.
 */

/**
 * Implements hook_help().
 */
function islandora_spreadsheet_ingest_help($path, $arg) {
  switch ($path) {
    case 'admin/islandora/tools/islandora_spreadsheet_ingest':
    case 'islandora_spreadsheet_ingest':
      return '<p>' . t('CSV files are expected to follow the core rules defined in <a href="https://www.ietf.org/rfc/rfc4180.txt">RFC 4180</a>, with configurable defaults overriding some of the specification in the case of poorly-formed CSV.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function islandora_spreadsheet_ingest_menu() {
  $menu = array();

  $menu['islandora_spreadsheet_ingest'] = array(
    'title' => 'Islandora Spreadsheet Ingest',
    'description' => 'Batch ingest objects via spreadsheet and template',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('use islandora spreadsheet ingest'),
    'page arguments' => array('islandora_spreadsheet_ingest_batch_form'),
    'file' => 'includes/batch.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['admin/islandora/tools/islandora_spreadsheet_ingest'] = array(
    'title' => 'Islandora Spreadsheet Ingest',
    'description' => 'Administer Islandora Spreadsheet Ingest',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer islandora spreadsheet ingest'),
    'page arguments' => array('islandora_spreadsheet_ingest_admin_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['admin/islandora/tools/islandora_spreadsheet_ingest/add_template'] = array(
    'title' => 'Add template',
    'description' => 'Upload a template.',
    'page callback' => 'drupal_get_form',
    'file' => 'includes/admin.form.inc',
    'page arguments' => array('islandora_spreadsheet_ingest_add_template_form'),
    'access arguments' => array('administer islandora spreadsheet ingest'),
    'type' => MENU_LOCAL_ACTION,
  );
  $menu['admin/islandora/tools/islandora_spreadsheet_ingest/%/delete_template'] = array(
    'title' => 'Delete template',
    'description' => 'Delete a template.',
    'page callback' => 'drupal_get_form',
    'file' => 'includes/admin.form.inc',
    'page arguments' => array('islandora_spreadsheet_ingest_delete_template_form', 4),
    'access arguments' => array('administer islandora spreadsheet ingest'),
    'type' => MENU_CALLBACK,
  );
  $menu['admin/islandora/tools/islandora_spreadsheet_ingest/%/update_template'] = array(
    'title' => 'Update template',
    'description' => 'Update a template.',
    'page callback' => 'drupal_get_form',
    'file' => 'includes/admin.form.inc',
    'page arguments' => array('islandora_spreadsheet_ingest_update_template_form', 4),
    'access arguments' => array('administer islandora spreadsheet ingest'),
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Implements hook_permission().
 */
function islandora_spreadsheet_ingest_permission() {
  return array(
    'administer islandora spreadsheet ingest' => array(
      'title' => t('Administer Islandora Spreadsheet Ingest'),
    ),
    'use islandora spreadsheet ingest' => array(
      'title' => t('Use Islandora Spreadsheet Ingest'),
    ),
  );
}
