<?php

/**
 * @file
 * Module API documentation.
 */

/**
 * Implements hook_islandora_spreadsheet_ingest_templates().
 */
function islandora_spreadsheet_ingest_example_islandora_spreadsheet_ingest_templates() {
  return array(
    array(
      'id' => 'sample_xslt',
      'name' => 'Sample XSLT',
      'uri' => drupal_get_path('module', 'islandora_spreadsheet_ingest_example') . '/includes/example_template.xslt',
      'dsids' => array('MODS'),
    ),
  );
}
