<?php

/**
 * @file
 * General hook implementations.
 */

const ISLANDORA_SPREADSHEET_INGST_NEWSPAPER_ISSUES_MODEL = 'islandora:newspaperIssueCModel';

/**
 * Implements hook_islandora_spreadsheet_ingest_object_alter().
 */
function islandora_spreadsheet_ingest_newspaper_issues_islandora_spreadsheet_ingest_object_alter(AbstractObject $object) {
  if (in_array(ISLANDORA_SPREADSHEET_INGST_NEWSPAPER_ISSUES_MODEL, $object->models)) {
    module_load_include('inc', 'islandora_spreadsheet_ingest', 'includes/utilities');
    _islandora_spreadsheet_ingest_newspaper_issues_sequence($object);
  }
}
