---
islandora_spreadsheet_ingest.settings:
  type: config_object
  mapping:
    binary_directory_whitelist:
      type: sequence
      label: 'List of allowed source directories.'
      sequence:
        type: string
    enable_config_ignore_integration:
      type: boolean
      label: 'If our config_ignore integration should be enabled.'
    schemes:
      type: sequence
      label: 'Allowed source URI schemes.'
      sequence:
        type: string
