<?php

/**
 * @file
 * Hook implementations.
 */

/**
 * Implements hook_islandora_spreadsheet_ingest_object_alter().
 */
function islandora_spreadsheet_ingest_compounds_islandora_spreadsheet_ingest_object_alter(AbstractObject $object) {
  $parents = $object->relationships->get(FEDORA_RELS_EXT_URI, variable_get('islandora_compound_object_relationship', 'isConstituentOf'));
  if (!empty($parents)) {
    module_load_include('inc', 'islandora_spreadsheet_ingest_compounds', 'includes/compound_order');
    foreach ($parents as $parent) {
      islandora_spreadsheet_ingest_compounds_order_constituent($object, $parent['object']['value']);
    }
  }
}
