<?php

/**
 * @file
 * General hook implementations.
 */

const ISLANDORA_SPREADSHEET_INGEST_SERIAL_ROOT = 'islandora:rootSerialCModel';
const ISLANDORA_SPREADSHEET_INGEST_SERIAL_INTERMEDIATE = 'islandora:intermediateCModel';
const ISLANDORA_SPREADSHEET_INGEST_SERIAL_STUB = 'islandora:intermediateSerialCModelStub';
const ISLANDORA_SPREADSHEET_INGEST_SERIAL_PDF = 'islandora:sp_pdf';
// const 'islandora:sequence_position';
//define('ISLANDORA_SERIAL_OBJECT_SEQUENCE_PREDICATE', 'sequence_position');
//define('ISLANDORA_SERIAL_OBJECT_PDF_PARENT_PREDICATE', 'isComponentOf');

/**
 * Implements hook_islandora_spreadsheet_ingest_object_alter().
 */
// function islandora_spreadsheet_ingest_newspaper_issues_islandora_spreadsheet_ingest_object_alter(AbstractObject $object) {
//   if (in_array(ISLANDORA_SPREADSHEET_INGST_NEWSPAPER_ISSUES_MODEL, $object->models)) {
//     module_load_include('inc', 'islandora_spreadsheet_ingest_newspaper_issues', 'includes/utilities');
//     _islandora_spreadsheet_ingest_newspaper_issues_sequence($object);
//   }
// }
