name: Code Linting
on:
  pull_request:
    branches:
      - 8.x-2.x

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run CodeSniffer
        uses: discoverygarden/CodeSniffer@v1
        with:
          path: ./
