---
name: Code Linting
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run CodeSniffer
        uses: discoverygarden/CodeSniffer@v1
